// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz7tkXyAeW5k3pgsArBBg0MyBMM20UWHM',
    appId: '1:686190759768:web:6ba41cf223182d5f7f5f2d',
    messagingSenderId: '686190759768',
    projectId: 'valporoom',
    authDomain: 'valporoom.firebaseapp.com',
    storageBucket: 'valporoom.appspot.com',
    measurementId: 'G-TST255T0TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl-zRMXlngA33JwGAGVO01CStlUp4I6ok',
    appId: '1:686190759768:android:2a46b6e1d2d4237f7f5f2d',
    messagingSenderId: '686190759768',
    projectId: 'valporoom',
    storageBucket: 'valporoom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3sN3jz2lC8i9haTeWlOLgNpCoyOTZO8Q',
    appId: '1:686190759768:ios:4dc6c03cf971e53a7f5f2d',
    messagingSenderId: '686190759768',
    projectId: 'valporoom',
    storageBucket: 'valporoom.appspot.com',
    iosClientId: '686190759768-6dc22rnq12fqhqe7njo8r890c2v73c2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.valporoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3sN3jz2lC8i9haTeWlOLgNpCoyOTZO8Q',
    appId: '1:686190759768:ios:07e6fe73a00c8ad47f5f2d',
    messagingSenderId: '686190759768',
    projectId: 'valporoom',
    storageBucket: 'valporoom.appspot.com',
    iosClientId: '686190759768-uqvi2kbnhgqtg8m2nrqjk8rvltnlvqel.apps.googleusercontent.com',
    iosBundleId: 'com.example.valporoom.RunnerTests',
  );
}
